<?php

namespace atc\SDG\Modules\Worship\Fields;

use atc\WXC\Core\Contracts\FieldGroupInterface;

final class SermonFields implements FieldGroupInterface
{
    public static function register(): void
    {
        if ( !function_exists('acf_add_local_field_group') ) return;
        
        acf_add_local_field_group( array(
			'key' => 'group_628d219d26000',
			'title' => 'Sermon: Additional Fields',
			'fields' => array(
				array(
					'key' => 'field_62bdde0aac636',
					'label' => 'Author',
					'name' => '',
					'aria-label' => '',
					'type' => 'tab',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'placement' => 'top',
					'endpoint' => 0,
					'selected' => 0,
				),
				array(
					'key' => 'field_64b15c0d258ae',
					'label' => 'Show author image in sermon archives?',
					'name' => 'author_image_for_archive',
					'aria-label' => '',
					'type' => 'true_false',
					'instructions' => 'If this box is checked AND an image has been saved to the author\'s person record, then that image will be displayed in the sermon archive instead of any featured image attached to the sermon record.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'relevanssi_exclude' => 0,
					'message' => '',
					'default_value' => 1,
					'ui' => 0,
					'ui_on_text' => '',
					'ui_off_text' => '',
				),
				array(
					'key' => 'field_65144a81d4712',
					'label' => 'Show author image on sermon page?',
					'name' => 'show_author_image',
					'aria-label' => '',
					'type' => 'true_false',
					'instructions' => 'If this box is checked AND an image has been saved to the author\'s person record, then that image will be displayed on the sermon record.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'relevanssi_exclude' => 0,
					'message' => '',
					'default_value' => 1,
					'ui' => 0,
					'ui_on_text' => '',
					'ui_off_text' => '',
				),
				array(
					'key' => 'field_628e3bfca7950',
					'label' => 'Sermon Author',
					'name' => 'sermon_author',
					'aria-label' => '',
					'type' => 'relationship',
					'instructions' => 'aka Preacher',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'post_type' => array(
						0 => 'person',
					),
					'taxonomy' => '',
					'filters' => array(
						0 => 'search',
						1 => 'taxonomy',
					),
					'elements' => '',
					'min' => '',
					'max' => '',
					'return_format' => 'object',
					'bidirectional_target' => array(),
				),
				array(
					'key' => 'field_62bdde1bac637',
					'label' => 'Event',
					'name' => '',
					'aria-label' => '',
					'type' => 'tab',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'placement' => 'top',
					'endpoint' => 0,
					'selected' => 0,
				),
				array(
					'key' => 'field_628e3c39a7951',
					'label' => 'Sermon Date',
					'name' => 'sermon_date',
					'aria-label' => '',
					'type' => 'date_time_picker',
					'instructions' => 'Date Delivered',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'display_format' => 'd/m/Y g:i a',
					'return_format' => 'Y-m-d H:i:s',
					'first_day' => 1,
				),
				array(
					'key' => 'field_628e3c5fa7952',
					'label' => 'Related Event',
					'name' => 'related_event',
					'aria-label' => '',
					'type' => 'relationship',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'post_type' => array(
						0 => 'event',
					),
					'taxonomy' => '',
					'filters' => array(
						0 => 'search',
						1 => 'taxonomy',
					),
					'elements' => '',
					'min' => '',
					'max' => '',
					'return_format' => 'object',
					'bidirectional_target' => array(),
				),
				array(
					'key' => 'field_63320afb66a22',
					'label' => 'Sermon Series (v2 bidirectional)',
					'name' => 'sermons_series',
					'aria-label' => '',
					'type' => 'relationship',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'post_type' => array(
						0 => 'sermon_series',
					),
					'taxonomy' => '',
					'filters' => array(
						0 => 'search',
					),
					'return_format' => 'object',
					'min' => '',
					'max' => '',
					'elements' => '',
					'bidirectional_target' => array(),
				),
				array(
					'key' => 'field_628e3ccea7956',
					'label' => 'Sermon Series (v1)',
					'name' => 'sermon_series',
					'aria-label' => '',
					'type' => 'relationship',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'post_type' => array(
						0 => 'sermon_series',
					),
					'taxonomy' => '',
					'filters' => array(
						0 => 'search',
					),
					'return_format' => 'object',
					'min' => '',
					'max' => '',
					'elements' => '',
					'bidirectional_target' => array(),
				),
				array(
					'key' => 'field_628e3d0ea7957',
					'label' => 'Sermon Series Number',
					'name' => 'sermon_series_num',
					'aria-label' => '',
					'type' => 'number',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'min' => '',
					'max' => '',
					'step' => '',
				),
				array(
					'key' => 'field_62bdde29ac638',
					'label' => 'Text',
					'name' => '',
					'aria-label' => '',
					'type' => 'tab',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'placement' => 'top',
					'endpoint' => 0,
					'selected' => 0,
				),
				array(
					'key' => 'field_628e3caca7954',
					'label' => 'Sermon Transcript PDF',
					'name' => 'sermon_pdf',
					'aria-label' => '',
					'type' => 'file',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'library' => 'all',
					'min_size' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array(
					'key' => 'field_628e3cc3a7955',
					'label' => 'Sermon Sidebar',
					'name' => 'sermon_sidebar',
					'aria-label' => '',
					'type' => 'wysiwyg',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'full',
					'media_upload' => 1,
					'delay' => 0,
				),
				array(
					'key' => 'field_62bdde3bac639',
					'label' => 'Scripture',
					'name' => '',
					'aria-label' => '',
					'type' => 'tab',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'relevanssi_exclude' => 0,
					'placement' => 'top',
					'endpoint' => 0,
					'selected' => 0,
				),
				array(
					'key' => 'field_628e3d1da7958',
					'label' => 'Scripture Citation(s)',
					'name' => 'scripture_citations',
					'aria-label' => '',
					'type' => 'relationship',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'post_type' => array(
						0 => 'reading',
					),
					'taxonomy' => '',
					'filters' => array(
						0 => 'search',
					),
					'elements' => '',
					'min' => '',
					'max' => '',
					'return_format' => 'object',
					'bidirectional_target' => array(),
				),
				array(
					'key' => 'field_63ecfd62b80ed',
					'label' => 'Books of the Bible',
					'name' => 'sermon_bbooks',
					'aria-label' => '',
					'type' => 'post_object',
					'instructions' => 'DO NOT EDIT. This field is auto-populated based on the selected readings.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => 'read-only',
						'id' => '',
					),
					'relevanssi_exclude' => 0,
					'post_type' => array(
						0 => 'bible_book',
					),
					'taxonomy' => '',
					'return_format' => 'object',
					'multiple' => 1,
					'allow_null' => 0,
					'ui' => 1,
					'bidirectional_target' => array(),
				),
				array(
					'key' => 'field_63ee561532187',
					'label' => 'Scripture Citation(s) (TXT)',
					'name' => 'scripture_citations_txt',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => 'DO NOT EDIT! This is a legacy field, for reference only.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => 'read-only',
						'id' => '',
					),
					'relevanssi_exclude' => 0,
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
			),
			'location' => array(
				array(
					array(
						'param' => 'post_type',
						'operator' => '==',
						'value' => 'sermon',
					),
				),
			),
			'menu_order' => 0,
			'position' => 'acf_after_title',
			'style' => 'default',
			'label_placement' => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen' => '',
			'active' => true,
			'description' => '',
			'show_in_rest' => 0,
		) );

    }
}
